# -*- coding: utf-8 -*-
"""Visualização final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TvXcq-jApiXhLClKPgB0Ls_bVEMPTAAT
"""

import pandas as pd
import plotly.express as px
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import folium
import json
from branca.colormap import linear

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/taxa_desemprego_br.csv',sep=';',decimal=',')
data.head(30)

Pais = "Brasil"
data.insert(loc=0,column='Pais',value=Pais)

data.head(5)

barras = data.query("Pais == 'Brasil'")
fig = px.bar(barras, x='Sigla', y='4º trimestre 2018', title="Porcentagem de desemprego nos Estados brasileiros em 2018")
fig.show()

data2 = pd.read_csv('/content/taxa_desemprego_br.csv', sep=';', decimal=',', usecols=['Sigla', '4º trimestre 2018'])
data2.head(3)

data2.rename(columns={
     'Sigla': 'Estado', 
     '4º trimestre 2018': '2018'}, inplace=True)
data2.head(3)

data2.describe()

colormap = linear.YlOrRd_09.scale(6,20)
colormap

data2_2018 = data2.set_index('Estado')['2018']

br_estados = '/content/br_states.json'
geo_json_data = json.load(open(br_estados))

mapa = folium.Map(
    width=600, height=400,
    location=[-15.77972, -47.92972], 
    zoom_start=4
)

folium.GeoJson(
    geo_json_data,
    name='2018',
    style_function=lambda feature: {
        'fillColor': colormap(data2_2018[feature['id']]),
        'color': 'black',
        'weight': 0.3,
    }
    
).add_to(mapa)

colormap.caption = 'Taxa de desemprego no Brasil em 2018'
colormap.add_to(mapa)
folium.LayerControl(collapsed=False).add_to(mapa)

mapa

anos= [2012, 2013, 2014, 2015, 2016, 2017, 2018]
taxa= [6.8,	6.5,	7.1,	10.1,	12.4,	12.7,	12.4]

fig = px.line(x=anos, y=taxa, title='Evolução do desemprego em SP em porcentagem por anos')
fig.show()